// PRODUCTS
export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FILTER_PRODUCTS_BY_SIZE = "FILTER_PRODUCTS_BY_SIZE";
export const ORDER_PRODUCTS_BY_PRICE = "ORDER_PRODUCTS_BY_PRICE";

// CART
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";

// ORDER
export const CREATE_ORDER = "CREATE_ORDER";
export const CLEAR_ORDER = "CLEAR_ORDER";
export const CLEAR_CART = "CLEAR_CART";

// ADMIN
export const FETCH_ORDERS = "FETCH_ORDERS";

// CART & MENU DISPLAY STATE OPEN/CLOSE
export const OPEN_CART = "OPEN_CART";
export const OPEN_CHECKOUT_FORM = "OPEN_CHECKOUT_FORM";

//CLOSE UP EVERYTHING BEFORE VIEWING ORDER FEEDBACK
export const CLOSE_UP = "CLOSE_UP";
